### ISSUE TITLE
Unable to install on Node 18 LTS

### ISSUE THREAD

**Issue by ZeroThe2nd** [edumudu/swr-vue#21]
The [package.json specifies](https://github.com/edumudu/swr-vue/blob/a5bc7f4f0ddf48baa1d98d564649d57e8337d556/package.json#L101) the Node engine to require version 16. With the release of NodeJS 18 LTS, this blocks installing of the package.

Is the engine intentionally locked down to 16, or would it be possible to change it to either include 18, or alternatively use 16 and up?

**Comment by edumudu** [comment]
It is not. Just published `1.9.1` with `"node": ">=16"`

**Comment by ZeroThe2nd** [comment]
Hmm, weird. I must've tried an install and checked the sauce right before that finished.
Thank you~ ^-^
